<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Students.aspx.cs" Inherits="Laborator_A2_3.Laborator4.Students1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="gdvstudents" runat="server"
               AutoGenerateColumns="false"
                 EmptyDataText="Nuk ka studente ne bazen e te dhenave"
                 DataKeyNames="StudentId"
                 DataMember="Student"
                  OnRowDataBound="gdvstudents_RowDataBound"
                  AutoGenerateDeleteButton="true" OnRowDeleting="gdvstudents_RowDeleting"  >
                <Columns>
                    <asp:BoundField ReadOnly="true"  Visible="false" DataField="StudentId" HeaderText="Id e studentit" />
                    <asp:BoundField  DataField="Emer" HeaderText="Emri i studentit" />
                    <asp:BoundField  DataField="Mbiemer" HeaderText="Mbiemri i studentit" />
                    <asp:TemplateField HeaderText="Regjistrimi per studentin">
                        <ItemTemplate>
                            <asp:Label ID="lblMessage" runat="server"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                     <asp:TemplateField HeaderText="Aksionet">
                        <ItemTemplate>
                            <asp:Button ID="Btmodifiko" runat="server" Text="Modifiko Student"  CommandName="ModifikoStudent"
                                 OnCommand="gdvButtons_Command"  Visible='<%#Laborator_A2_3.Laborator4.Students1.Visibility_Edit_Button()%>'
                                 CommandArgument='<%# ((Laborator_A2_3.Student)Container.DataItem).StudentId %>'
                                />
                             <asp:Button ID="btnDetail" runat="server" Text="Detai Student"  CommandName="DetailStudent"
                                 OnCommand="gdvButtons_Command"
                                 CommandArgument='<%# ((Laborator_A2_3.Student)Container.DataItem).StudentId %>'
                                />

                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:BoundField  DataField="EnrollmentDate" HeaderText="Data e regjistrimit"  DataFormatString="{0:dd/MM/yyyy}" />
                </Columns>

            </asp:GridView>

            <asp:Button runat="server" ID="LogOut" Text="LogOut" OnClick="LogOut_Click" />


        </div>
    </form>
</body>
</html>
