<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Students.aspx.cs" Inherits="Laborator_A2_3.Laborator4.Students" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="gdvStudent" DataKeyNames="StudentId"
                DataMember="Student"
                AutoGenerateColumns="false" AutoGenerateDeleteButton="true"
                OnRowDeleting="gdvStudent_RowDeleting"
                OnRowDataBound="gdvStudent_RowDataBound"
                 EmptyDataText="Nuk ka asnje student ne databaze"
                runat="server">
                <Columns>
                    <asp:BoundField ReadOnly="true" Visible="false" DataField="StudentId" HeaderText="Id e studentit" />
                    <asp:BoundField DataField="Emer" HeaderText="Emri i studentit" />
                    <asp:TemplateField HeaderText="Rezultati i regjistrimit">
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lbMsg"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:BoundField DataField="Mbiemer" HeaderText="Mbiemri i studentit" />
                    <asp:BoundField DataField="EnrollmentDate" HeaderText="Data e Regjistrimit"
                        DataFormatString="{0:dd/MM/yyyy}" />
                    <asp:TemplateField HeaderText="Aksionet">
                        <ItemTemplate>
                            <asp:Button ID="btnModify" runat="server" Text="Modifiko Student"
                                CommandArgument='<%#((Laborator_A2_3.Student)Container.DataItem).StudentId.ToString()%>'
                                CommandName="ModifikoStudent"
                                OnCommand="gdvButtons_Command" />
                            &nbsp;
                             <asp:Button ID="btnDetail" runat="server" Text="Detail Student"
                                CommandArgument='<%#((Laborator_A2_3.Student)Container.DataItem).StudentId.ToString()%>'
                                CommandName="DetailStudent"
                                OnCommand="gdvButtons_Command" />
                        </ItemTemplate>


                    </asp:TemplateField>

                </Columns>


            </asp:GridView>

        </div>
    </form>
</body>
</html>
