//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborator_A2_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Authorization
    {
        public int Id { get; set; }
        public Nullable<int> AuthorizationId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual User User { get; set; }
    }
}
